# Generated by Django 5.1 on 2024-09-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='descripcion',
        ),
    ]
