# Generated by Django 5.1 on 2024-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descripcion',
            field=models.CharField(default='01-09-2024 13:22', max_length=200),
            preserve_default=False,
        ),
    ]
