# Generated by Django 5.1 on 2024-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_wide',
            field=models.BooleanField(default=False),
        ),
    ]
